### ISSUE TITLE
Kodi Leia - Random video freeze and buffering on live tv start and channel switch

### ISSUE THREAD

**Issue by puenktchen** [xbmc/xbmc#14828]
### Describe the bug
Here is a clear and concise description of what the problem is:

On Nvidia Shield TV with Kodi Leia and DVBViewer pvr addon i get random buffering either when starting live tv or after channel switch. The video picture freezes, but audio is still playing in the background.
After about 5 seconds audio is also stopping and after another small delay (the buffering delay here depends on the GetStreamReadChunkSize parameter size) live tv is working as expected.
It doesn't happen always on the same channels, but more on some then the others.
It doesn't matter if the channels are sd mpeg2 or hd hevc. It only happens with live tv, not recordings,
library videos or other streams. The Shield is hardwired with Gbit LAN.
It has never happened on Kodi Krypton!

## Expected Behavior
No video picture freeze or buffering is expected.

## Actual Behavior
Random video picture freeze and buffering on live tv start and channel switching

### To Reproduce

1. Install Kodi Leia on Nvidia shield TV
2. Install and set up DVBViewer pvr addon
3. Start Live TV

### Debuglog

The debuglog can be found here: https://www.dropbox.com/s/4h7jwxkk5csrro0/kodi.log?dl=0

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Shield Android TV SW-Version 7.1.0 "Oreo" 
 - Kodi version: 18.0-RC1 Git:20181106-5c2918003c-dirty

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by M2k80** [comment]
same problem but with enigma2 plugin reported here too 
https://github.com/xbmc/xbmc/issues/14804

**Comment by puenktchen** [comment]
Not exactly the same, but yes it's similar. I don't get a black screen or Kodi hanging.
There are also similar reports from NextPVR, ServerWMC and MediaPortal users in the forum.
Something that fixed some problems that where reported by Tvheadend users with Kodi Krypton,
which are happy now, seems to have a bad side affect for other pvr addons.
Only the devs know...

**Comment by Leatherface75** [comment]
This sounds like my problem when using VAAPI deinterlace modes here on Intel hardware and TVheadend server.

**Comment by M2k80** [comment]
@puenktchen Black screen and hang forever, is another problem. It happens not so much. 
Watch the video I made, this is the normal what happens.

**Comment by ksooo** [comment]
> Something that fixed some problems that where reported by Tvheadend users with Kodi Krypton,
which are happy now, seems to have a bad side affect for other pvr addons.

 How could you know that?

**Comment by ksooo** [comment]
<pre>
19:48:06.051 T:178208597232   DEBUG: CDVDVideoCodecAndroidMediaCodec::AddData dts:576766.67 pts:696766.67 sz:37249 indexBuffer:2 current state (3)
19:48:11.812 T:178257249520    INFO: AddOnLog: DVBViewer Client: Performing forced EPG update!
19:48:11.912 T:178284303600   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:0.000000
19:48:13.320 T:178284303600   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:-0.050000
19:48:14.100 T:178285339888  NOTICE: CVideoPlayerAudio::Process - stream stalled
19:48:14.102 T:178284303600   DEBUG: Stream stalled, start buffering. Audio: 0 - Video: 100
19:48:14.102 T:178284303600   DEBUG: CVideoPlayer::FlushBuffers - flushing buffers
</pre>

Hmm, maybe the EPG update while playing the channel is stressing the machine so much that it can't deliver stream data fast enough? Just guessing. There is a setting to prevent epg updates while playing. Does that help?

**Comment by manuelm** [comment]
`forced EPG update` is triggered on channel switch only. And it's only updating the channel the user has switched to (maybe I should make this debug message a bit clearer). Imho Kodi already prevented the EPG update. Otherwise there would be a HTTP requests to `../api/epg.html`.

**Comment by puenktchen** [comment]
> > Something that fixed some problems that where reported by Tvheadend users with Kodi Krypton,
> > which are happy now, seems to have a bad side affect for other pvr addons.
> 
> How could you know that?

I don't know it! It's only an assumption. Or better a personal conclusion from reading through the forum.

**Comment by puenktchen** [comment]
> 19:48:06.051 T:178208597232   DEBUG: CDVDVideoCodecAndroidMediaCodec::AddData dts:576766.67 pts:696766.67 sz:37249 indexBuffer:2 current state (3)
> 19:48:11.812 T:178257249520    INFO: AddOnLog: DVBViewer Client: Performing forced EPG update!
> 19:48:11.912 T:178284303600   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:0.000000
> 19:48:13.320 T:178284303600   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:-0.050000
> 19:48:14.100 T:178285339888  NOTICE: CVideoPlayerAudio::Process - stream stalled
> 19:48:14.102 T:178284303600   DEBUG: Stream stalled, start buffering. Audio: 0 - Video: 100
> 19:48:14.102 T:178284303600   DEBUG: CVideoPlayer::FlushBuffers - flushing buffers
> Hmm, maybe the EPG update while playing the channel is stressing the machine so much that it can't deliver stream data fast enough? Just guessing. There is a setting to prevent epg updates while playing. Does that help?

It's like it was recognized by @manuelm, i've already disabled the standard epg update while playing live tv.

**Comment by FernetMenta** [comment]
> 19:48:14.102 T:178284303600 DEBUG: Stream stalled, start buffering. Audio: 0 - Video: 100

this indicates an Android Mediacodec issue.

**Comment by puenktchen** [comment]
> > 19:48:14.102 T:178284303600 DEBUG: Stream stalled, start buffering. Audio: 0 - Video: 100
> 
> this indicates an Android Mediacodec issue.

You are probably right. I cannot reproduce it with software decoding only.
But the question is, why does it work in Krypton?

**Comment by puenktchen** [comment]
@peak3d Can you please have a look?

**Comment by peak3d** [comment]
I guess its this one.

19:48:04.601 T:178208597232   DEBUG: CDVDVideoCodecAndroidMediaCodec::AddData dts:-63233.33 pts:-63233.33 sz:11554 indexBuffer:6 current state (3)

Androids PTS is uint64_t

**Comment by puenktchen** [comment]
So is this something that can be fixed in Kodi, maybe by you?

**Comment by peak3d** [comment]
We first have to figure out if / why DTS / PTS values are negative.
Negative DTS Values "could" make sense, negative PTS IMO not.

We clarify the internals in our internal team chat, we'll come back with a solution

**Comment by M2k80** [comment]
just tested a little under windows and there are negative pts too?
the effect after a channel change is not so big like on nvidia shield, but there is a small frame freeze after channel switch.
https://paste.ubuntu.com/p/GFQpPS6wQd/

**Comment by phunkyfish** [comment]
Using libreelec on intel and also see some occasional buffering and negative pts values. Different log message though. Just wondering if it could be related.

10:31:27.683 T:140716876568320   DEBUG: VideoPlayer::Sync - Audio - pts: -611066.000000, cache: 516711.826785, totalcache: 800000.011921
10:31:27.684 T:140716876568320   DEBUG: VideoPlayer::Sync - Video - pts: 18442240474082181120.000000, cache: 50000.000000, totalcache: 100000.000000
10:33:24.492 T:140716903843584   DEBUG: VideoPlayer::Sync - Audio - pts: 156933.000000, cache: 513523.291452, totalcache: 800000.011921
10:33:24.492 T:140716903843584   DEBUG: VideoPlayer::Sync - Video - pts: 777333.000000, cache: 50000.000000, totalcache: 100000.000000
10:33:44.562 T:140716903843584   DEBUG: VideoPlayer::Sync - Audio - pts: 20380933.000000, cache: 470051.192172, totalcache: 800000.011921
10:33:44.562 T:140716903843584   DEBUG: VideoPlayer::Sync - Video - pts: 18442240474082181120.000000, cache: 50000.000000, totalcache: 100000.000000
10:33:46.142 T:140716903843584   DEBUG: VideoPlayer::Sync - Audio - pts: 21692933.000000, cache: 320000.052452, totalcache: 800000.011921
10:33:46.142 T:140716903843584   DEBUG: VideoPlayer::Sync - Video - pts: 18442240474082181120.000000, cache: 50000.000000, totalcache: 100000.000000
10:35:18.532 T:140716912236288   DEBUG: VideoPlayer::Sync - Audio - pts: -667066.000000, cache: 517992.603119, totalcache: 800000.011921
10:35:18.533 T:140716912236288   DEBUG: VideoPlayer::Sync - Video - pts: 18442240474082181120.000000, cache: 50000.000000, totalcache: 100000.000000
10:36:19.535 T:140716878665472   DEBUG: VideoPlayer::Sync - Audio - pts: 238511.000000, cache: 509004.022771, totalcache: 800000.011921
10:36:19.536 T:140716878665472   DEBUG: VideoPlayer::Sync - Video - pts: 332522.000000, cache: 50000.000000, totalcache: 100000.000000
10:37:15.229 T:140716920628992   DEBUG: VideoPlayer::Sync - Audio - pts: -177488.000000, cache: 508657.982437, totalcache: 800000.011921
10:37:15.229 T:140716920628992   DEBUG: VideoPlayer::Sync - Video - pts: -67477.000000, cache: 50000.000000, totalcache: 100000.000000

**Comment by gilesp1729** [comment]
I am getting a similar problem, new on Leia, starting live TV there is no video, the Music OSD comes up instead, or else video freezes for ~10 seconds and audio is out of sync. Eventually comes good after a couple of channel changes. Leia beta5 or RC1 (doesn't happen in Krypton), LibreELEC Rpi backend. Have debug log if interested (long, not sure which bits are relevant, but none of the above sync messages)

**Comment by peak3d** [comment]
@puenktchen can you pls. try this build?

https://jenkins.kodi.tv/job/Android-ARM64/8350/artifact/kodi-20181126-aae62ebb-PR14950-merge-arm64-v8a.apk

**Comment by puenktchen** [comment]
> @puenktchen can you pls. try this build?
> 
> https://jenkins.kodi.tv/job/Android-ARM64/8350/artifact/kodi-20181126-aae62ebb-PR14950-merge-arm64-v8a.apk

Just a question: Has this apk an unique application id, so that i can install it side by side?

**Comment by puenktchen** [comment]
Really well done @peak3d!
For me the problem is solved.

**Comment by peak3d** [comment]
Please close

**Comment by Qlink84** [comment]
do i have to open up a new issue, because my problem still persists.... ?(https://github.com/xbmc/xbmc/issues/14828#issuecomment-441783762)
