### ISSUE TITLE
Resume Button on video with x265 codec produces Black Screen on Android TV

### ISSUE THREAD

**Issue by mytril** [xbmc/xbmc#15250]
### Describe the bug
Here is a clear and concise description of what the problem is:

If you want to watch a video with x265 codec, all works fine. But if you  want to reload the video to the point till you  watched (Replay Button), there is no Picture (Black Screen), only Audio and GUI are visible.

On videos with other codecs all works fine and on windows it works with x265 too.

Systeminformations:
Kodi 18 RC 5.2
Android 7 
Sony KD-55AF8

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should replay the video without black screen

## Possible Fix

1. It could have to do with the video buffer 

2. or with the video settings
because if you play the video, on video settings, the video scaling method field is not there and if you replay it, there is the video scaling method field.

### To Reproduce

1. Start Kodi on Sony TV KD-55AF8
2. Watch a video with x265 codec
3. Stop it at any time
4. Replay it

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ebejafakel

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have tryed other codecs, which work fine
I have tryed other Platforms (Windows, Android 7.1.1 Smartphone) which work fine.
I have tryed to stop the video again or fast forward it which doesn't make it better. The audio is on the right place but no video output come up.
I have tryed different versions of Kodi. On 17.6 it does function, but on 18 RC 2 and RC5.2 but i have tryed no other versions.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: 7 Nougat
 - Kodi version: 18 RC 2 and RC 5.2
- Device Name: Sony TV KD-55AF8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mytril** [comment]
On the Final 8 Version, it doesn't working too.

**Comment by MartijnKaijser** [comment]
Can you try a new nightly build?

**Comment by mytril** [comment]
I have tryed now the newest nightly from today "kodi-20190210-d9ed9408-master-armeabi-v7a.apk". But it is still the same problem

**Comment by mytril** [comment]
The new logfile is here: [https://paste.kodi.tv/leromeleha](https://paste.kodi.tv/leromeleha)

**Comment by nsadovskiy** [comment]
Confirm bug for Kodi 18.1 on Android TV 8.0.0 on Sony KD-43XF8096. Same video transcoded to x264 works fine.  My debug log is here: [https://paste.kodi.tv/wewizuyavu.kodi](https://paste.kodi.tv/wewizuyavu.kodi). 
Original video (in x265 encoding) resumed normally on the build-in android video player on the same TV.

**Comment by mytril** [comment]
I have tested now Version "kodi-20190322-5033b6fd-master-armeabi-v7a.apk" and still the same problem.

**Comment by mytril** [comment]
The Bug is still in the final 18,2 Version. Nothing chaged

**Comment by pkerling** [comment]
@mytril You will be notified if something changes.

**Comment by mytril** [comment]
I have found out, that if you feed the x265 encoder with the parameter "uhd-bd" you get a larger file, but also the resume function is fixed.

I have also found out, that the problem only shows up in mkv files, not with mp4-

**Comment by certen42** [comment]
This issue is still unsolved. This problem only appears in 1080p x265 files. 
There is no problem with 4k x265 files.

**Comment by Lazulent** [comment]
I have the same problem Sony KD49XE9005 Android TV.  VLC player on the TV will resume with no problem.  Firestick HD on another TV will resume with no problem.  Kodi 18.5 1080p x265 gives black screen on mkv and mp4 files.

**Comment by guelcki79** [comment]
Same problem on Sony TV still occurs with Kodi 18.6.

**Comment by johnyb0y** [comment]
I can confirm this on the FireTV 4K 2015 with Kodi 18.7. 
**The behavior somewhat changed with 18.7**: With earlier versions Kodi would often hang or even crash when trying to resume x265 videos. 
With 18.7 it now starts playing the audiotrack while showing a black screen with the player controls. I am then able to stop the playback again.

**Comment by johnyb0y** [comment]
Update: With Kodi 18.8 this is fixed for me on my Fire TV 4K 2015! 
I can now resume HEVC content without problems. 
Wow, didn’t expect that! 👍

**Comment by Lazulent** [comment]
Works on my Firestick 4K and Windows 64k.  Still doesn't work on my Android TV but VLC player works on the same TV.  Apologies for the delay, it takes time for the update to appear on GooglePlay.

**Comment by Lazulent** [comment]
The problem still exists on the Sony 55XE90xx.

**Comment by guelcki79** [comment]
Kodi 18.9, still the same problem.

**Comment by tmrony** [comment]
Kodi 19 has no such issue. My sony xe85 can resume x265 nicely with kodi 19

**Comment by Lazulent** [comment]
Good to hear.  I will wait for the Release version and get back.

**Comment by mytril** [comment]
I also can confirm this. With the beta version of kodi 19, my kd55-af8 can also now resume x265 videos.
