### ISSUE TITLE
Android TV "Play" remote button not working during fast forward

### ISSUE THREAD

**Issue by mctinker** [xbmc/xbmc#15395]
### Describe the bug
When watching a video (e.g. TV program episode, when I fast forward and then hit the "Play" button on my Logitech 650 remote, nothing happens other than the program continues to fast forward.

The Logitech remote has a "Play" (top/toggle-up) and "Pause" (bottom/toggle-down) button.   Hitting this "Play"/toggle-up button on the remote with any beta RC v18 appears to have no impact...the video continues to fast forward.
 
Others on Android TV are experiencing the same problem. Refer to...
[https://forum.kodi.tv/showthread.php?tid=340030&pid=2816051#pid2816051]

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

While the video is fast forwarding, I should be able to hit the remote's "Play"/toggle-up button to stop the fast forward action and have the video continue playing from it's currently forwarded position.  With Kodi 17, hitting the "Play"/toggle-up would stop the fast forward process and start playing the video starting at the location to which it had forwarded.  

## Actual Behavior

While fast forwarding, hitting the remote's "Play"/toggle-up button has no impact on the fast forward process.

## Possible Fix

Properly configured keymap.xml file for Android TV?  I looked for this file on my TV and could not find it.  Perhaps the default PlayControl setting is wrong/missing.
 
Note: with the Logitech 650 remote, there is also an "Ok" button, which when depressed brings up the navigation UI from which pause and play can then be selected.

### To Reproduce

1. Play a video on Android TV
2.Hit fast-foward
3.Hit "Play" button

### Debuglog

The debuglog can be found here:
https://www.dropbox.com/s/zjb9trnb1kz0ou1/kodi.log?dl=0
...starting around time-stamp 14:22:38.867

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by mctinker** [comment]
Sony TV: XBR-55x930D with latest Android firmware v5.417

**Comment by DaVukovic** [comment]
You have banned addons and repositories installed. Please remove them completely, reproduce your error and get us new logfile

This issue will be closed in 3 days if new log is submitted.

**Comment by mctinker** [comment]
Okay, I believe I have deleted all of the banned add-ons and repositories.
 
I have uploaded a new log file to the location identified above.
 
If there are still banned add-ons/repositories indicated in the log, please identify them for me, as well as how to locate and delete them.

**Comment by mctinker** [comment]
Uploaded a new log since I realized the File Manager still had some illegal repositories ... which I first deleted.

**Comment by mctinker** [comment]
On most recent log, I fast forwarded the video, then hit the "Play" button on the remote several times to no avail.  I then hit the "Ok" button on the remote to bring up the navigation UI, and then selected the "pause" icon to stop the fast forward action.

**Comment by DaVukovic** [comment]
You still have leftovers from banned add-ons in your log. 

Please make sure you are using a completely vanilla Kodi. Best would be to do a fresh install if you don´t know how to get rid of it.

Still invalid

**Comment by mctinker** [comment]
Okay.  Did a complete, clean install of Kodi (force stop, clear data, uninstall, reinstall).
 
Recreated the problem: fast-forwarded, hit Play button 3 times, hit return and then stop to stop the fast forwarding.  New log, above, posted.

**Comment by nadav74** [comment]
I have this problem too, but this is not the only problem - there are quite a few of them (I have a Sony Bravia x85 Android TV): "Play" does not behave as "play-pause" anymore, but as only as "play". Meaning, it will not pause a played file. I think this is the root cause of this issue. I tried to browse the commits for remote.xml as well as IRTranslator.{cpp|h} for a reason for this regression but couldn't find it.

Provided that there's a suggested change I can test it pretty quickly with a patch since I have my own development environment and can install own apks.

**Comment by mctinker** [comment]
Can I at least get the "INVALID" tag off this issue?

**Comment by mctinker** [comment]
I am unable to recreate this problem with the past couple of builds.  It appears that this bug has been fixed.  
 
Is anyone else still having this problem?  If not, I will close it in three days.

**Comment by nadav74** [comment]
I'll try the latest git version.

**Comment by nadav74** [comment]
YES, this is fixed! I just wonder what fixed it, as I followed check-ins and could not see which it was that fixed it.

**Comment by mctinker** [comment]
Re-booted my TV today and the problem is back with, what I assume to be, a new code drop.  The symptom is slightly different: when hitting the play button while fast forwarding, the bottom of the screen shows the keymap: pause, ff, settings, etc. and the text display summary off the show I am watching.
 
I will keep this problem open pending a more permanent fix.

**Comment by mctinker** [comment]
Above comment (problem is back) refers to build: Kodi 18.1 Git:201990311-a456bde2ef compiled 2019-03-11.

**Comment by mctinker** [comment]
Picked up build 3/21 and the problem is fixed once again.
 
I will go through one more build cycle to ensure this stays fixed before closing this bug.

**Comment by mctinker** [comment]
I picked up the new build 0401 tonight (Git 20190401 45401ec4a6) and the "Play" button now works correctly again.
 
I'll wait for the next build to verify the fix is truely in before closing this out.

**Comment by mctinker** [comment]
I have confirmed with others that this reported problem is no longer an issue.  
 
The odd behavior I was experiencing (keymap and text box) was due to a second, identical remote with identical Harmony firmware but which is not working quite the same as the other remote.
 
I am closing this issue as resolved.
