### ISSUE TITLE
Kodi 18.0 fails to load https webdav servers

### ISSUE THREAD

**Issue by Rezer** [xbmc/xbmc#15478]
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi can no longer access https webdav servers.  When attempting to open one, it simply says "Couldn't connect to network server".  I tested this in both android and windows, and verified that the same exact server still works when accessing it via web browser and kodi 17.6.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expected it to load the file index of the webdav server and list what's available.

## Actual Behavior

It fails when when reading the certificate and never tries to access the file listing.

### To Reproduce

1.  Create a webdav server secured with an SSL certificate (Specifically a PositiveSSL Comodo cert in this case).  Unsure if relevant, but it's configured to listen on port 8082.
2. Verify the webdav server is accessible via a web browser and the certificate is setup correctly
3. Enter the server details in kodi and attempt to connect.
4. Observe kodi failing to connect

### Debuglog

The debuglog can be found here (I prefer not to list my domain publicly so those details are redacted):

https://pastebin.com/y6gjERU1

This log contains several attempts to connect, and I believe the relevant lines are as follows:

19:41:07.921 T:13128   ERROR: CCurlFile::FillBuffer - Failed: Peer certificate cannot be authenticated with given CA certificates(60)
19:41:07.921 T:13128   ERROR: CCurlFile::Open failed with code 0 for https://exampledomain.us:8082/ExampleFolder/:
19:41:07.921 T:13128   ERROR: XFILE::CDAVDirectory::GetDirectory - Unable to get dav directory (davs://USERNAME:PASSWORD@exampledomain.us:8082/ExampleFolder/)
19:41:07.921 T:13128   ERROR: XFILE::CDirectory::GetDirectory - Error getting davs://USERNAME:PASSWORD@exampledomain.us:8082/ExampleFolder/
19:41:07.922 T:9724   ERROR: CGUIMediaWindow::GetDirectory(davs://USERNAME:PASSWORD@exampledomain.us:8082/ExampleFolder/) failed

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Certificate issuer if that matters?
CN = COMODO RSA Domain Validation Secure Server CA
O = COMODO CA Limited
L = Salford
ST = Greater Manchester
C = GB

Algorithm:
PKCS #1 SHA-256 With RSA Encryption

Expires in 2020

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

Server is a FreeNAS 10 box, using the built in webdav server configuration,

 - Operating system version/name:
 - Kodi version: 18.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by pkerling** [comment]
Possibly fixed by #15441, can you try a nightly?

**Comment by arnova** [comment]
And if not fixed, please enable Curl logging component and post a new debug log.

**Comment by Rezer** [comment]
I downloaded the latest nightly, 18.1-RC1 Git:20190210-d9ed9408c4, and the issue still exists.  I have an updated debug log with libCurl logging enabled:

https://pastebin.com/rJ3kVN5V

**Comment by pkerling** [comment]
Assumption: You fail to include a required intermediate certificate. Can you verify this please?

For comparison purposes: Does access with a cleanly installed Firefox work?

**Comment by Rezer** [comment]
> 
> 
> Assumption: You fail to include a required intermediate certificate. Can you verify this please?
> 
> For comparison purposes: Does access with a cleanly installed Firefox work?

Like I said, this setup works fine using Kodi 17.6, and it does load up as expected in both firefox and chrome.  The site comes up with the SSL padlock displayed and I can view that the certificate is valid in both browsers.

**Comment by Rezer** [comment]
If there's something else you'd like me to check to verify the existence of the appropriate intermediate certificate, I'd be happy to provide that, but other than verifying that SSL encryption works properly using other applications I'm unsure of where to look.  My understanding is that you simply need a trusted root certificate available on the machine and the chain of trust to the site cert can be verified with nothing else required.

**Comment by pkerling** [comment]
> Like I said, this setup works fine using Kodi 17.6

That does not mean anything. v17 did not check the certificate.

> My understanding is that you simply need a trusted root certificate available on the machine and the chain of trust to the site cert can be verified with nothing else required.

That is not correct unfortunately. Many CAs sign the final certificates that you use with an intermediary CA that you also have to include in your server configuration in order for the client to be able to establish the chain of trust. This is also the case here (I assume browsers might cache the intermediary if you have visited any site that served it, so that is also not a definite answer unless you try on a completely clean install). The intermediary certificate "COMODO RSA Domain Validation Secure Server CA" is not included in the CA package, but the trust root "COMODO RSA Certification Authority" is. So if you have not set up your server to include the intermediary, it is obvious that it cannot work. Please refer to the documentation of your server and cert provider on how to do that.

**Comment by wsnipex** [comment]
how to verify on a shell:
openssl -showcert -connect hostname:port

**Comment by Rezer** [comment]
> That does not mean anything. v17 did not check the certificate.

Hoo boy, I had no idea, that kinda destroys my whole justification for thinking this was a bug in the first place.  I went ahead and followed your suggestion of including the intermediate, and sure enough that resolves the issue.  Very sorry for the confusion, but I'd like to think I wasn't completely off the rails assuming if it worked in 16 and 17 something must have been broken in 18, even though the exact opposite is true.

> openssl s_client -showcerts -connect hostname:port

I've been running off this configuration for a couple years now and never had any issues on any machine with any method I've used of accessing the share until now, so I had no idea my ssl configuration had this flaw.  Will that command always identify ssl config errors?  I ran it on the current configuration and it still says it could not get local issuer certificate, but maybe that's because I didn't include the root cert in my config and that command doesn't have any trusted certs built in?

Anyway, closing this.

**Comment by pkerling** [comment]
> I've been running off this configuration for a couple years now and never had any issues on any machine with any method I've used of accessing the share until now, so I had no idea my ssl configuration had this flaw.

Takeaway: SSL is hard :-)

> I ran it on the current configuration and it still says it could not get local issuer certificate, but maybe that's because I didn't include the root cert in my config and that command doesn't have any trusted certs built in?

Depends on what OS/platform you are running it on. If you have a regular Linux distro, it uses the regular system CA store. It works for me.
