### ISSUE TITLE
Kodi 18.1 keeps crashing

### ISSUE THREAD

**Issue by stifani** [xbmc/xbmc#15762]
### Describe the bug
Issues with kodi 18.1! It keeps random crashing after the 2nd start up. More specific: In a clean PC environment, install kodi and when executing, it works and often after half an hour of use, it randomly crash; but running it again and again, most of the time it crashes after 4-5 seconds!!
So the first time of execution in a clean environment IT ALWAYS works, but running again for a second or a third time, it ends up with a crash after 4 or 5 seconds after launched!! It's completely random and annoying!!

## Expected Behavior
Kodi not to crash

## Actual Behavior
kodi crash

## Possible Fix
See https://forum.kodi.tv/showthread.php?tid=341809 as suggested by @davilla

### To Reproduce

1. Start kodi
2. Close kodi
3. Restart kodi

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/owaqokuwen.kodi
https://paste.kodi.tv/ivaverovuc.kodi
https://paste.kodi.tv/uqatoteyaz.kodi (this is the crash dump log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

See https://forum.kodi.tv/showthread.php?tid=341809

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 7 x86 SP1
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KarellenX** [comment]
Did you see the solution from @davilla ? Was it not of use to you?

Also you have ignored the required template to submit an issue here. Please edit your first post and re-add the template, or close this issue and start a new one.

**Comment by stifani** [comment]
I've added the template. So now it's ok. About the suggestion of @davilla, I think that is the problem with CEvent event and it should be easy for programmers to fix that. I've just reported also here on github.

**Comment by kib** [comment]
Direct link to @davilla 's comment in https://forum.kodi.tv/showthread.php?tid=341809&pid=2834838#pid2834838 

```wow, I know this crash Smile It's a design fault with CEvent that gets triggered under a very particular set of conditions.

The easiest fix is to make "CEvent event" a member var and side-step the dtor race with WaitMSec. Add a heavy dose of comments so no one decides to 'optimize' the fix away.```

**Comment by davilla** [comment]
The problem is in void CEvent::Set()
Once signaled is set and the lock is left, then you have a race. The CEvent obj can be deleted before the rest of the code runs if you have the Set in a different thread.  Removing the {} around the lock/signaled = true is wrong, it will deadlock under other situations. Maybe inverting the order ? We just made the CEvent a member var of CApplication, so it is never destructed.

**Comment by DaVukovic** [comment]
@davilla could you confirm this issue is also fixed by #15801 ?

**Comment by davilla** [comment]
#15801 does not fix the issue with racing in CEvent::Set() with CEvent::WaitMSec

**Comment by DaVukovic** [comment]
Is this issue stil present on current master?
@davilla @stifani ?
