### ISSUE TITLE
Kodi segfault'ing on second call of json-rpc Addons.ExecuteAddon method

### ISSUE THREAD

**Issue by bacon-cheeseburger** [xbmc/xbmc#17776]
### Describe the bug

Kodi is segfaulting on the second use of the json-rpc Addons.ExecuteAddon method. I tested with both ReloadSkin() and Mute. Two reloads, two mutes, reload then mute, mute then reload, it doesn't matter. The second call always crashes. Both calls always return ``{"id":1,"jsonrpc":"2.0","result":"OK"}``. 

To check if it was just the Addons.ExecuteAddon method, I did multiple json-rpc calls to the Settings.GetSettingValue method and they were all handled fine, no crash.

The Addons.ExecuteAddon calls don't have to be consecutive. For example, you can call Addons.ExecuteAddon to reload the skin, then call Settings.GetSettingsValue to get the current resolution, then call Addons.Execute.Addon to mute and it will crash on the mute.

The exact commands I sent are:

curl -X POST -H "content-type:application/json" http://localhost:8080/jsonrpc -d '{ "jsonrpc": "2.0", "id": 1, "method": "Addons.ExecuteAddon", "params": { "addonid": "script.toolbox", "params": { "info": "builtin", "id": "ReloadSkin()" } } }'

curl -X POST -H "content-type:application/json" http://localhost:8080/jsonrpc -d '{ "jsonrpc": "2.0", "id": 1, "method": "Addons.ExecuteAddon", "params": { "addonid": "script.toolbox", "params": { "info": "builtin", "id": "Mute" } } }'

 curl -X POST -H "content-type:application/json" http://localhost:8080/jsonrpc -d '{"jsonrpc":"2.0", "method":"Settings.GetSettingValue","params":{"setting":"videoscreen.resolution"}, "id":1}'

I'm using Kodi compiled from git a couple days ago (cdb887b088) with script.toolbox version="2.0.0" installed from within the GUI. 

## Expected Behavior

I expected Kodi to execute the second ReloadSkin call rather than crash.

## Actual Behavior

Kodi segfaults on the second call to the Addons.ExecuteAddon method. The calls do not have to be consecutive.

### To Reproduce

1. Start Kodi.
2. Issue a valid json-rpc call using the Addons.ExecuteAddon method and allow it to finish.
3. Issue another valid json-rpc call using the Addons.ExecuteAddon method.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/gacovukuyi.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian Sid Linux
 - Kodi version: 19.0-ALPHA1-git+cdb887b088

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by enen92** [comment]
Made a few tests with this and I was able to reproduce. However, if we remove the dependency on python-pil it works just fine. This is probably related to python binary modules or the usage of PIL in script.toolbox

**Comment by enen92** [comment]
Backtrace:

```
Backtrace:
4   libSDL-1.2.0.dylib                  0x00000001269db3c7 QZ_UnsetVideoMode + 983
5   libSDL-1.2.0.dylib                  0x00000001269d9397 QZ_VideoQuit + 279
6   libSDL-1.2.0.dylib                  0x00000001269ca4f3 SDL_VideoQuit + 115
7   libSDL-1.2.0.dylib                  0x000000012698f719 SDL_QuitSubSystem + 169
8   libSDL-1.2.0.dylib                  0x000000012698f79e SDL_Quit + 14
9   libsystem_c.dylib                   0x00007fff6b1ab143 __cxa_finalize_ranges + 326
10  libsystem_c.dylib                   0x00007fff6b1ab412 exit + 55
11  _imaging.cpython-37-darwin.so       0x0000000133b10c45 add_item + 133
12  _imaging.cpython-37-darwin.so       0x0000000133b106c7 ImagingAccessInit + 23
13  _imaging.cpython-37-darwin.so       0x0000000133b028e2 setup_module + 162
14  _imaging.cpython-37-darwin.so       0x0000000133b02816 PyInit__imaging + 38
15  kodi.bin                            0x00000001076f7c83 _PyImport_LoadDynamicModuleWithSpec + 579
16  kodi.bin                            0x00000001076f76d0 _imp_create_dynamic + 352
17  kodi.bin                            0x0000000107606ca1 _PyMethodDef_RawFastCallDict + 609
18  kodi.bin                            0x0000000107606758 PyCFunction_Call + 200
19  kodi.bin                            0x00000001076d3f58 _PyEval_EvalFrameDefault + 14024
20  kodi.bin                            0x00000001076d7ffd _PyEval_EvalCodeWithName + 3021
21  kodi.bin                            0x0000000107606469 _PyFunction_FastCallKeywords + 217
22  kodi.bin                            0x00000001076d726c call_function + 780
23  kodi.bin                            0x00000001076d39ad _PyEval_EvalFrameDefault + 12573
24  kodi.bin                            0x000000010760698d function_code_fastcall + 237
25  kodi.bin                            0x00000001076d726c call_function + 780
26  kodi.bin                            0x00000001076d29b2 _PyEval_EvalFrameDefault + 8482
27  kodi.bin                            0x000000010760698d function_code_fastcall + 237
28  kodi.bin                            0x00000001076d726c call_function + 780
29  kodi.bin                            0x00000001076d43e7 _PyEval_EvalFrameDefault + 15191
30  kodi.bin                            0x000000010760698d function_code_fastcall + 237
31  kodi.bin                            0x00000001076d726c call_function + 780
32  kodi.bin                            0x00000001076d43e7 _PyEval_EvalFrameDefault + 15191
33  kodi.bin                            0x000000010760698d function_code_fastcall + 237
34  kodi.bin                            0x00000001076d726c call_function + 780
35  kodi.bin                            0x00000001076d43e7 _PyEval_EvalFrameDefault + 15191
36  kodi.bin                            0x00000001076d7ffd _PyEval_EvalCodeWithName + 3021
37  kodi.bin                            0x0000000107606469 _PyFunction_FastCallKeywords + 217
38  kodi.bin                            0x00000001076d726c call_function + 780
39  kodi.bin                            0x00000001076d39ad _PyEval_EvalFrameDefault + 12573
40  kodi.bin                            0x000000010760698d function_code_fastcall + 237
41  kodi.bin                            0x00000001076d726c call_function + 780
42  kodi.bin                            0x00000001076d43e7 _PyEval_EvalFrameDefault + 15191
43  kodi.bin                            0x00000001076d7ffd _PyEval_EvalCodeWithName + 3021
44  kodi.bin                            0x00000001076d07f0 PyEval_EvalCode + 48
45  kodi.bin                            0x00000001076f5758 PyImport_ExecCodeModuleObject + 264
46  kodi.bin                            0x000000010777ab1e zipimport_zipimporter_load_module + 462
47  kodi.bin                            0x0000000107607207 _PyMethodDef_RawFastCallKeywords + 775
48  kodi.bin                            0x000000010760d201 _PyMethodDescr_FastCallKeywords + 81
49
=================================================================
Main Thread Checker: UI API called on a background thread: -[NSWindow close]
PID: 67890, TID: 1158866, Thread name: LanguageInvoker, Queue name: com.apple.root.default-qos.overcommit, QoS: 0
```

This happens as long as we do:

`from PIL import Image, ImageOps` for the second time. It would be interesting to test this with the new version of PIL.

**Comment by enen92** [comment]
Ok, good news. This will be solved once PIL is updated to version 5.1.0

https://github.com/xbmc/xbmc/pull/17794

Whenever @fuzzard decides to pick it up again :)

**Comment by fuzzard** [comment]
@enen92 Ive got the failing platforms all sorted in that PR now. From what i remember, someone had said 7.1.2 PIL fails with this as well?

If i run up an OSX build with 7.1.2, are you able to test and verify if it works/fails? Ideally ill want to bump to 7.1.2 in that PR, but if it fails, maybe just leave at 5.1.0 for now.

**Comment by fuzzard** [comment]
@enen92 Ive done some cleanups, and ive also added a commit to bump to 7.1.2

There are some jenkins artifacts for a 5.1.0 build, as well as a 7.1.2 (building atm)

https://jenkins.kodi.tv/job/BuildMulti-PR/16309/ - 5.1.0
https://jenkins.kodi.tv/job/BuildMulti-PR/16311/ - 7.1.2

You can get osx/android artifacts from the job. Can you test this issue is resolved in 1, or hopefully both versions?

Ive runtime both on ios, so they should function, but confirmation on another platform is always good.

**Comment by ccope** [comment]
Just saw the PR got merged, hoping it'll get backported to Leia

**Comment by enen92** [comment]
@ccope @bacon-cheeseburger can you confirm the problem is fixed in current master?

**Comment by bacon-cheeseburger** [comment]
I just compiled a fresh Kodi git 19.0-ALPHA1-git+466b13ecf8. Kodi is still crashing as described in the initial report using the same tests. The current matrix repo script.toolbox has `addon="script.module.pil" version="1.1.7"`. /usr/local/share/kodi/addons/script.module.pil/addon.xml has `id="script.module.pil", name="Python Image Library", version="5.1.0"`. 

Please let me know if I can do anything on my end to help further, or if any more info is needed!

**Comment by malard** [comment]
Re-triaged this while working through the JSON-RPC backlog. It isn't a JSON-RPC bug, so I'm unassigning myself and leaving it with Component: Python.

### Why `Addons.ExecuteAddon` isn't implicated

`CAddonsOperations::ExecuteAddon` resolves the add-on, concatenates `params` into an argv string, formats `RunAddon(<id>, <argv>)`, and hands that to the application messenger — `SendMsg` when `params["wait"]` is set, `PostMsg` otherwise. The message is then executed on the main thread by `CBuiltins::Execute`.

That is the identical builtin a keymap entry, a skin `<onclick>` or a GUI launch produces. The handler keeps no state between calls, so the second call differs from the first only in that a script has already run once in the process. Launching the same add-on twice by any other route should fail the same way; JSON-RPC just makes it convenient to do twice in a row.

### Where the fault actually is

`CPythonInvoker::execute` creates a fresh sub-interpreter per invocation (`Py_NewInterpreter()`, `PythonInvoker.cpp`) and `onExecutionDone` tears it down (`Py_EndInterpreter`, preceded by a `PyDict_Clear` of the module dict). `RunScript` calls `ExecuteAsync` with the default `reuseable = false`, so a second launch never takes the thread-state reuse path and always builds a new sub-interpreter — which re-imports the add-on's C extension modules.

That is exactly where @enen92's backtrace faults: inside `PyInit__imaging` under `_PyImport_LoadDynamicModuleWithSpec`. PIL's `_imaging` is a single-phase-init extension, which has never been safe to load into more than one sub-interpreter. Kodi uses legacy shared-GIL sub-interpreters, where the check that would reject such a module is off, so it loads anyway. Still true of Pillow 12.3.0 — a strict sub-interpreter rejects it outright with `ImportError: module PIL._imaging does not support loading in subinterpreters`.

So the underlying issue is Kodi running script add-ons in legacy sub-interpreters, not the method used to launch them.

### Status on current master — not verified

I did not get to a reproduction, so I can't say whether this still bites. Two things have changed since the report, both worth checking before anyone spends time on it:

* **Interpreter version.** Kodi 22 builds against Python 3.14 (`PYTHON3-VERSION` = 3.14.6; `python314.dll` on Windows), against 3.8 when this was filed. CPython reworked its handling of single-phase-init extension modules in sub-interpreters substantially over 3.9–3.12. As a standalone check outside Kodi, importing Pillow 12.3.0 into three successive *legacy* sub-interpreters on CPython 3.13 — clearing `sys.modules` between each, approximating what `onExecutionDone` does — ran clean every time. That is suggestive, not proof.
* **The original reproducer can no longer be assembled.** `script.toolbox` 2.0.0 is still published and still declares `<import addon="script.module.pil" version="1.1.7"/>`, but `script.module.pil` is no longer in the add-on repository at all, so the dependency cannot resolve on a current Kodi. Reproducing now needs a hand-built script add-on bundling some current single-phase-init C extension.

Given the reporter's environment no longer exists and the CPython-side handling has moved on, this may well be stale — but it should be confirmed with an actual run rather than closed on the reasoning above.
