### ISSUE TITLE
Reversed punctuation in RTL subtitles in Kodi 19

### ISSUE THREAD

**Issue by baerlein** [xbmc/xbmc#18648]
### Describe the bug
Here is a clear and concise description of what the problem is:

Punctuation is reversed when using Hebrew subtitles in Kodi 19. This is a common issue with RTL (right to left) languages but it used to work properly in Kodi 18.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Punctuation should be placed at the end of the sentence, see attached screenshot for reference.

## Actual Behavior

Punctuation is placed in the beginning of the sentence.

### To Reproduce

1. Change language in Player settings to Hebrew, character set to Hebrew (Windows).
2. Place attached subtitle file "Hebrew_subs.srt" in same dir of a video named accordingly (e.g. "Hebrew_subs.mp4").
3. Play the video in Kodi

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/aqunebojuw.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Reference screenshot:

![screenshot](https://user-images.githubusercontent.com/49202713/97198537-97502c80-17b7-11eb-92f3-7027f893d8a2.jpg)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Sample subtitle file:

[Hebrew_subs.zip](https://github.com/xbmc/xbmc/files/5440000/Hebrew_subs.zip)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64, Android
 - Kodi version: Kodi 19.0 "Matrix" - Release

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by baerlein** [comment]
This is still an issue with Kodi 19 beta 1.

**Comment by nirmv77** [comment]
I confirm that it's still in issue in Kodi 19 beta 1.
BTW I'm using kodi on Android.

**Comment by EyalRotem** [comment]
as of beta 2 this is still an issue. (windows)

**Comment by nirmv77** [comment]
Hi, this is still an issue in RC1 (Android)

**Comment by EyalRotem** [comment]
> Hi, this is still an issue in RC1 (Android)

Yes, on windows as well

**Comment by shmizan** [comment]
can someone take a look at this? it's a real problem.

**Comment by Obi-Wan-Aloni** [comment]
Joining the request to look into this.
Will gladly help on anything I can.

**Comment by enen92** [comment]
Provide a sample, a screenshot identifying/explaining the problem and explain what should happen instead. I doubt we have any Hebrew, Arabic, etc team members.

**Comment by enen92** [comment]
nvm, all is in the bug report.

**Comment by EyalRotem** [comment]
yes, @baerlein actually did a thorough job. so if anything else is needed, let us know and we'll try to help.

it seems that in addition the problem is cross-platform (as @nirmv77 says it's on android as well). 
and as mentioned - 18.9 and bellow worked good without the issue that was introduced in 19+

**Comment by GuyKh** [comment]
It looks the issue here is the RTL alignment.

**Comment by Nir-Zigler** [comment]
The problem is also in v19 GA. It's a bad regression from v18. hope it will be fixed soon...

**Comment by perditi0nspam** [comment]
Can confirm for Android box running newly installed Kodi 19. Subtitles which previously worked correctly for Hebrew (just a few days ago) now have reversed punctuation.

**Comment by naamapps** [comment]
Can also confirm, xiaomi mi box s, kodi 19, Hebrew subtitles have reversed punctuation.

**Comment by ztslil** [comment]
confirmed - fire tv stick 4k, kodi 19 latest release, subtitles that are working on 18.9, not working anymore.

**Comment by LiorAmram** [comment]
Confirmed - Nvidia Shield 2019 pro, kodi 19 latest release.

**Comment by itrigalo** [comment]
confirmed - Xiaomi mi box s, kodi 19, Hebrew subtitles have reversed punctuation

**Comment by cred-o** [comment]
confirmed - Nvidia shield pro 2019 - Kodi 19 latest release

**Comment by EyalRotem** [comment]
> This is still an issue with Kodi 19 beta 1.

Can you update the issue with the new information?
(Latest Kodi release, Android as well)

**Comment by reuvenwittenberg** [comment]
Windows 10, reverse punctuation! It's a shame, ther first time KODI got it wrong, and we need it badly!

**Comment by EyalRotem** [comment]
> Windows 10, reverse punctuation! It's a shame, ther first time KODI got it wrong, and we need it badly!

Stuff like this happens, especially when so much has changed (moving to python 3, adding hdr support and more).

I just wish this would be assigned to someone so at least it would be looked over.
No progress ha been made since the bug was reported 🤷🏼‍♂️

**Comment by enen92** [comment]
From https://forum.videolan.org/viewtopic.php?f=2&t=14063

The punctuation ordering problem is solved by calling fribidi with LTR as the main direction. This is a work-around. Since most players (under Windows) don't perform bidi, but let the system do it, the subtitles are prepared in logical order (RTL), but with main order (LTR), since players don't support setting the main order of the subtitles. This makes authoring subtitles a little harder, but everyone's already doing it.

In case anyone wants to look at this

**Comment by enen92** [comment]
@EyalRotem most likely a regression from https://github.com/xbmc/xbmc/pull/17790

**Comment by EyalRotem** [comment]
> @EyalRotem most likely a regression from #17790
> You fix one, you break another :)
> 
> Maybe @AhmedAdelAbouzeid has any idea

That just might be relevant, in any case- Ahmed probably has more idea about the subject as he already coded in kodi and uses an RTL language.

let’s hope this can be fixed with ease.

another thought- since python 3 is now incorporated- it really changes how strings and Unicode is handled, this might also be a cause.

**Comment by EyalRotem** [comment]
Alright! 
thank you @AhmedAdelAbouzeid for the quick response !

What version is this going to be on?
I guess now it’s on the nightly, but will 19.1 (for example) incorporate this fix?

thanks again for the fast work 💪🏼

**Comment by AhmedAdelAbouzeid** [comment]
Happy to help!
The previous PR was against master branch.

I have a PR open against Matrix branch now; after it is merged, the change can be tested in the next Matrix nightly build (tomorrow?)
http://mirrors.kodi.tv/nightlies/windows/win64/Matrix/
I have no idea about release versions though.

**Comment by EyalRotem** [comment]
In the 12/03/2021 nightly for windows 64, subtitles are fixed!
Waiting for the stable release now!

thanks for the effort @enen92 and @AhmedAdelAbouzeid  !

**Comment by Shimronfio** [comment]
Any updates for a working version for Android TV? 
I still got the issue on KODI 19.0 on Nvidia Shield Pro.

**Comment by EyalRotem** [comment]
> Any updates for a working version for Android TV?
> I still got the issue on KODI 19.0 on Nvidia Shield Pro.

The fix has been pushed.
So it’s up to the Kodi team- it will be incorporated in the next release.
Or you could maybe install the nightly build if you wish

**Comment by ntzb** [comment]
> Happy to help! The previous PR was against master branch.
> 
> I have a PR open against Matrix branch now; after it is merged, the change can be tested in the next Matrix nightly build (tomorrow?) http://mirrors.kodi.tv/nightlies/windows/win64/Matrix/ I have no idea about release versions though.

I see that this code is indeed already inside master branch, but the nightlies of master still show reversed punctuation.
is something else needed to fix this in master?

**Comment by scott967** [comment]
I once looked at this in regards libass, and after studying it I believe the code is working as designed, and looking at some fansubs it looked like they take it into account when subbing.  but I  don't remember the details now.
