### ISSUE TITLE
Nexus crash in Video Library thumb creation

### ISSUE THREAD

**Issue by emveepee** [xbmc/xbmc#20968]
### Describe the bug
Here is a clear and concise description of what the problem is:

Nexus crashes in video library creating thumbs with 

```
2022-02-08 08:45:41.438 T:15740   ERROR <general>: SQL: [MyVideos120.db] SQLite error SQLITE_ERROR (no such column: NaN)
                                                   Query: INSERT INTO streamdetails (idFile, iStreamType, strVideoCodec, fVideoAspect, iVideoWidth, iVideoHeight, iVideoDuration, strStereoMode, strVideoLanguage,  strHdrType)VALUES (23,0,'h264',NaN,0,0,48,'','','') (no such column: NaN)
2022-02-08 08:45:41.438 T:15740   ERROR <general>: CVideoDatabase::SetStreamDetailsForFileId (23) failed
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

In issues with specific files should not cause program to abor.t

## Actual Behavior

Program aborts with Windows error
```
Faulting application name: kodi.exe, version: 19.90.101.0, time stamp: 0x62008fe1
Faulting module name: ntdll.dll, version: 10.0.22000.469, time stamp: 0x931cda92
Exception code: 0xc0000374
Fault offset: 0x000000000010c0a9
Faulting process id: 0x324
Faulting application start time: 0x01d81cf225662f16
Faulting application path: D:\Nexus\kodi.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: d4eda958-ac76-46ee-8015-fd6e500cc028
Faulting package full name: 
Faulting package-relative application ID: 
```

### To Reproduce

Many files cause this issue just opening and scanning a video library

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/zudiqiwiwu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Windows 11

 - Kodi version:
Kodi Nexus nightlies.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by a1rwulf** [comment]
Apparently it fails to properly read the aspect ratio for some of your files.
You have NaN where fVideoAspect should be which is supposed to be a float.
Guess we should fix that NaN thingy and furthermore check why aspect ratio can't be read.

**Comment by cronlabspl** [comment]
@a1rwulf There are plenty of online converters that easily converts `NaN` to basically whatever format you dream of.

**Comment by enen92** [comment]
@emveepee fixed by https://github.com/xbmc/xbmc/pull/21810?

**Comment by emveepee** [comment]
@enen92 I regularly get garbage sample files from users and the paste expired so I don't know if the file is around to check.  I checked some other samples and it still crashes, but they location may be different now, files crash here https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp#L532  but the reason is more obvious since  I get this->m_pFormatContext->**streams** was nullptr  exception and the assumption that any mpegts file is valid is wrong.  For this error I can now easily duplicate it simply my naming a text file as .ts  

I do have a garbage ts file that are unplayable, that also crashes with the same error if you want.

**Comment by enen92** [comment]
@emveepee please provide the samples if possible

**Comment by emveepee** [comment]
> @emveepee please provide the samples if possible

Rename any non-mpeg file to a .ts extension and it will crash, it doesn't have to video. Do you need more than that?

**Comment by enen92** [comment]
Oops my bad, misinterpreted the "I do have a garbage ts file that are unplayable, that also crashes with the same error if you want." as some valid sample.

**Comment by emveepee** [comment]
> Oops my bad, misinterpreted the "I do have a garbage ts file that are unplayable, that also crashes with the same error if you want." as some valid sample.

The one I found is a valid ts file but there are no media streams in it so it still needs the nullptr test.

**Comment by howie-f** [comment]
that sql error: no such column NaN, is indeed odd
