### ISSUE TITLE
Misplaced brackets in RTL subtitles in Kodi 20.1

### ISSUE THREAD

**Issue by NeoCipher** [xbmc/xbmc#23364]
### Describe the bug
Here is a clear and concise description of what the problem is:

There is a bug that causes the brackets in RTL subtitles in Arabic language to be misplaced when there is a period or an exclamation mark after the word in brackets. A screenshot and a subtitle file are attached for reference.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The subtitles should display correctly with the brackets enclosing the word or name as intended.

## Actual Behavior

The subtitles display incorrectly with one bracket next to the word and the other one at the start of the subtitle line. This is usually noticed when there is a period or an exclamation mark after the word in brackets, but not when there is a question mark.

## Possible Fix

N/A

### To Reproduce

1. Install Kodi 20.1 on a TV device running Android OS.
2. Download the subtitle file that is attached to this report and place it in the same folder as the video file. [[ARABIC WINDOWS].zip](https://github.com/xbmc/xbmc/files/11666457/ARABIC.WINDOWS.zip)
3. Inside Settings/Player/Subtitles, select Arial Unicode MS for the Font and select the Arabic (Windows) for the Character set.
4. Play the video file with the subtitle file in Kodi.
5. Observe the subtitles on the screen.

### Debuglog

The debuglog can be found here:
N/A

### Screenshots
Here are some links or screenshots to help explain the problem:

![Screenshots](https://github.com/xbmc/xbmc/assets/81776316/8ca27dac-403c-444f-8e6d-548c411f1f8e)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This bug does not occur in VLC app on TV. It is unknown if this bug occurs in Kodi 20 RC2, but Kodi 20 RC2 had other issues with RTL subtitles in general.

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9 (Pie)
 - Kodi version: 20.1 (20.1.0) Git: 20230312-289ec664e3 Compiled: 2023-03-11

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by scott967** [comment]
Concur that there is an issue.  From observing the symptoms, it appears that the bidi algorithm is not being properly applied for Bidi Bracket Pairs per UAX #9 rule N0.

**Comment by scott967** [comment]
Background for preceding comment:
srt subtitle convention is to assume LTR base direction and assume bidi algorithm will properly render subtitle text.  I use the subtitle file kindly provided by issue author which appears to be encoded Windows-1256.  Looking at the subtitle at 00:20:24,890 what I see is the basic bidi algorithm generates 3 directional runs: LTR consisting of neutral chars "--"
RTL consisting of all additional characters up to the final ")" then a final LTR run of just ")"  My guess is that final ")" should be associated with the prior RTL run, but I'm not sure ATM what rule makes that happen.

**Comment by CastagnaIT** [comment]
i have already see this problem in the past that has been posted somewhere by another user looks like not so common these files

however when character set setting is used, whole file data is converted in advance here
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleStream.cpp#L81-L86
and then the passing of data to the parsers takes place,
atm i have no other suggestions on how to proceed

**Comment by scott967** [comment]
Here is output of bidi reference algo for that line of text after conversion to utf-8:
[Imgur](https://i.imgur.com/9uA9BZB.jpg)
that was run in on-line tester https://util.unicode.org/UnicodeJsps/bidic.jsp

**Comment by scott967** [comment]
@CastagnaIT  looking at the output of the online tester, it seems pretty clear the problem is step N0 of the algorithm, bracket matching, is not being done and as a result the parenthesis pairs are split in a later step between directional runs.  I notice this PR on libass:  https://github.com/libass/libass/pull/409  which sure looks like a possible cause if the feature is not set.

**Comment by CastagnaIT** [comment]
yeh we can make an attempt with enable ASS_FEATURE_BIDI_BRACKETS
i make a test locally in next week

**Comment by CastagnaIT** [comment]
i tested it these are the results (00:20:24):
VLC:
![VLC](https://github.com/xbmc/xbmc/assets/3257156/10816c35-f640-43f5-a9f7-e03cc5965547)
Kodi 21:
![Kodi21](https://github.com/xbmc/xbmc/assets/3257156/e79b1302-7559-4814-81dc-52254ba80e72)
Kodi 21 with ASS_FEATURE_BIDI_BRACKETS:
![Kodi21Mod](https://github.com/xbmc/xbmc/assets/3257156/67a100cb-0fa8-4adc-b578-0d4a358f363d)

seem good
and now another problem, our kodi libass prebuilts for windows are old, and also lack of a C++ extern to allow use this configuration

we need to build and publish new libass prebuilts to all windows platforms in advance
(this problem is only for windows because all other os use last libass version from upstream)

a lot of time ago i had already updated our patched branch
https://github.com/xbmc/libass/tree/kodi-17.1
but when i asked for help on slack to update windows prebuilts no one answered me to tell me how to do it

**Comment by CastagnaIT** [comment]
fixed, unfurnately i cant apply the fix on kodi 20 but only on next kodi 21

if someone give a feedback you can find apk's here:
https://jenkins.kodi.tv/job/android-arm64-docker/2500/
https://jenkins.kodi.tv/job/android-arm-docker/2620/

**Comment by NeoCipher** [comment]
It seems that a misplaced brackets behavior still appears whenever a bracket is right before a comma, though the bracket appears fine right before a period.
