### ISSUE TITLE
Auto play feature does not work when default select action is "show information"

### ISSUE THREAD

**Issue by TriVoxel** [xbmc/xbmc#23455]
### Describe the bug
Here is a clear and concise description of what the problem is:

When I have the "Default select action" set to "Show information", auto play feature does not work at all.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I want to have my videos auto play even when I have the select option set to "Show information". I like seeing show info before playing it, mostly for movies.

## Actual Behavior

When the episode ends, it just backs out of the show instead of auto playing the next episode.

## Possible Fix

Please allow auto play functionality even when something is played through the info menu with this setting enabled.

### To Reproduce

1. Open Settings 
2. Navigate to Player>Videos>Actions and set "Play next video automatically" to true for all values
3. Back out to main Settings page
4. Navigate to Media>Videos>All and set "Default select action" to "Show information"
5. Play any episode that is part of a season and skip to the end. It will not auto play the next episode but will just boot you back to the episode select screen.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 38 Workstation, GNOME (AMD64)
 - Kodi version: 20.1.0 (from 2023-03-18) Flatpak release

**Comment by ksooo** [comment]
> Play any episode that is part of a season and skip to the end. 

How exactly do you start the playback? Context menu item, play button on your remote/keyboard, ...?

**Comment by TriVoxel** [comment]
> > Play any episode that is part of a season and skip to the end.
> 
> How and where exactly do you start the playback? Context menu item, play button on your remote/keyboard, ...? From TV shows window, from Estuary Home Screen, ...?

Hi, sorry for not specifying. I use a 360 controller. So, this happens when I'm in a season of my show, and I press X on my controller to play from the context menu, as well as when I simply press the select button on an episode to bring up the info, then press play there. IDK about estuary or TV shows window, but at the very least where I'm used to going to start an episode being to open the show up, navigate to the last episode watched (or a specific episode to binge from), and click play, it normally has auto play, now it doesn't.

**Comment by TriVoxel** [comment]
Ideally I can click an episode or movie in a group, view the information beforehand, play it and enjoy my sjow uninterrupted. Also, thanks for the timely response, and big thanks to the XBMC/KODI team, this software is amazing!

**Comment by ksooo** [comment]
>  So, this happens when I'm in a season of my show, and I press X on my controller to play from the context menu

This should be fixed already in a recent Kodi Omega nightly build

> as well as when I simply press the select button on an episode to bring up the info, then press play there.

I can reproduce the problem and have a fix in the pipeline.

**Comment by TriVoxel** [comment]
@ksooo hey, I'm in 20.2.0 and I still have this issue. Has the fix been merged into this stable release, or is it going to be part of a next major release?

**Comment by ksooo** [comment]
Next major only. Required code changes are to big, thus to risky for Nexus backport.
