### ISSUE TITLE
Reversed punctuation in RTL subtitles in Kodi 20 

### ISSUE THREAD

**Issue by test01203** [xbmc/xbmc#23679]
### Describe the bug
Punctuation is reversed when using Hebrew subtitles in Kodi 20
Likely applies to all other RTL languages too.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Punctuation should be placed at the end of the sentence, see attached screenshot for reference.

## Actual Behavior
Punctuation is placed in the beginning of the sentence.

### To Reproduce
Change subtitles language in Player settings to Hebrew, character set to Hebrew (Windows).
Place attached subtitle file [Hebrew_subs.zip](https://github.com/xbmc/xbmc/files/10348200/Hebrew_subs.zip) in same dir of a video named accordingly (e.g. "Hebrew_subs.mp4").
Play the video in Kodi

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:
![image](https://github.com/xbmc/xbmc/assets/104188844/c70a5656-65a9-4391-8a86-98c26f7d544f)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
https://github.com/xbmc/xbmc/issues/22398

### Your Environment
Used Operating system:

 - [V ] Android
 - [V ] iOS
 - [ V] tvOS
 - [V ] Linux
 - [ V] macOS
 - [V ] Windows
 - [ V] Windows UWP

 - Operating system version/name:
 - Kodi version: kodi 20

**Comment by enen92** [comment]
@CastagnaIT this was fixed for v21 right?

**Comment by The-cpu-max** [comment]
> @CastagnaIT this was fixed for v21 right?

No
The problem also exists in version 21

**Comment by test01203** [comment]
> @CastagnaIT this was fixed for v21 right?

I downloaded version 21 from the site and still have the same problem

**Comment by CastagnaIT** [comment]
yes has been fixed on both kodi 20 and 21,
ofc if the srt dont follow the reversed punctuation "standard" then the text will be displayed wrong
as said on this comment https://github.com/xbmc/xbmc/issues/22398#issuecomment-1433027418

**Comment by test01203** [comment]
> yes has been fixed on both kodi 20 and 21, ofc if the srt dont follow the reversed punctuation "standard" then the text will be displayed wrong as said on this comment [#22398 (comment)](https://github.com/xbmc/xbmc/issues/22398#issuecomment-1433027418) and then user must fix his srt, subtitles software can apply automatic fixes for these cases
> 
> fwik there is no way to accomodate both ways (with or without reversed punctuation) at least on my long researches i havent found, so better keep support the most used

Hi, it only works fine with external subtitles
But in built-in subtitles it shows this inverted question mark and comma

**Comment by CastagnaIT** [comment]
this is not you have written in the description and the steps to reproduce are then wrong,
also you should provide a sample video where we can try test

**Comment by test01203** [comment]
I thought my problem was known
Look I made a video when I play built-in translation it shows this comma on the other side
And when I change to external subtitles it works fine

https://github.com/xbmc/xbmc/assets/104188844/83390bd5-5ae2-44eb-a3df-e31a2695ddaf

**Comment by CastagnaIT** [comment]
we dont need a desktop recording, we need the file to test
which can be a slice of your or you can send another similar sample

**Comment by TwilightMercy** [comment]
This is not Kodi bug, which was for Kodi 20.0 but fixed from 20.1, these are the internal subtitles in the files that uploaded with reversed punctuation.

Is there any way to access with python the subtitles text to modify it?

**Comment by scott967** [comment]
I suppose with pyffmpeg you could extract text-based sub streams and maybe pysubs2 has method for this (haven't looked at it at all for this).

**Comment by test01203** [comment]
> we dont need a desktop recording, we need the file to test which can be a slice of your or you can send another similar sample



> I suppose with pyffmpeg you could extract text-based sub streams and maybe pysubs2 has method for this (haven't looked at it at all for this).

Well, really after checking, the problem is with the subtitles themselves
What I would like to know is whether it is possible to automatically reverse commas and question marks? Of course with built-in subtitles?
